name: fastapi_test
version: "3.8"
services:
  fastapi_server:
    build:
      context: /home/cc/restaurant-recommender/monitoring         # path to your project root with Dockerfile
      dockerfile: Dockerfile
    container_name: fastapi_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /mnt/object/user_latent_vectors:/app/data/user_latent_vectors:ro
      - /mnt/object/item_latent_vectors:/app/data/item_latent_vectors:ro
    ports:
      - "8000:8000"
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  # HTTP port for FastAPI