name: fastapi_test
services:
  fastapi_server:
    build:
      context: .         # Use current directory as the build context
      dockerfile: Dockerfile
    container_name: fastapi_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /mnt/object/user_latent_vectors:/app/data/user_latent_vectors:rw
      - /mnt/object/item_latent_vectors:/app/data/item_latent_vectors:rw
    networks:
      - monitoring_network
    ports:
      - "8000:8000"
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - monitoring_network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - monitoring_network
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring_network:
    driver: bridge