{
 "title": "RecSys Service Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "RecSys average request duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1000 * rate(http_request_duration_seconds_sum{handler=\"/recommend\", job=\"recsys\"}[1m]) / \nrate(http_request_duration_seconds_count{handler=\"/recommend\", job=\"recsys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RecSys request duration percentiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler=\"/recommend\"}[1m]))",
     "legendFormat": "{{Median}}"
    },
    {
     "expr": "1000*histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"/recommend\"}[1m]))",
     "legendFormat": "{{95th percentile}}"
    },
    {
     "expr": "1000*histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler=\"/recommend\"}[1m]))",
     "legendFormat": "{{99th percentile}}"
    }
   ]
  },
  {
   "title": "RecSys requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/recommend\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RecSys error status and failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/recommend\", status=\"4xx\"}[1m])",
     "legendFormat": "{{error status}}"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/recommend\", status=\"5xx\"}[1m])",
     "legendFormat": "{{failed requests}}"
    }
   ]
  }
 ]
}