FROM python:3.9-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the transform script
COPY scripts/transform.py scripts/

# Set Python to run in unbuffered mode
ENV PYTHONUNBUFFERED=1

CMD ["python", "scripts/transform.py"] 